In [1]:
import pandas as pd

In [2]:
clustering_results = pd.read_csv('ind4_exp_matrix_with_clusters.csv.gz', compression='gzip')

In [3]:
clustering_results

,RP11.34P13.3,FAM138A,OR4F5,RP11.34P13.7,RP11.34P13.8,RP11.34P13.14,RP11.34P13.9,FO538757.3,FO538757.2,AP006222.2,...,BX072566.1,AL354822.1,AC023491.2,AC004556.1,AC233755.2,AC233755.1,AC240274.1,AC213203.1,FAM231B,cluster_label
0,0,0,0,0.0,0,0,0,0,0.0,0.000000,...,0,0.0,0,0.0,0,0,0.0,0,0,2
1,0,0,0,0.0,0,0,0,0,0.0,0.000000,...,0,0.0,0,0.0,0,0,0.0,0,0,2
2,0,0,0,0.0,0,0,0,0,0.0,0.000000,...,0,0.0,0,0.0,0,0,0.0,0,0,1
3,0,0,0,0.0,0,0,0,0,0.0,0.592736,...,0,0.0,0,0.0,0,0,0.0,0,0,3
4,0,0,0,0.0,0,0,0,0,0.0,0.000000,...,0,0.0,0,0.0,0,0,0.0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009,0,0,0,0.0,0,0,0,0,0.0,1.382332,...,0,0.0,0,0.0,0,0,0.0,0,0,0
4010,0,0,0,0.0,0,0,0,0,0.0,0.000000,...,0,0.0,0,0.0,0,0,0.0,0,0,3
4011,0,0,0,0.0,0,0,0,0,0.0,0.000000,...,0,0.0,0,0.0,0,0,0.0,0,0,0
4012,0,0,0,0.0,0,0,0,0,0.0,0.000000,...,0,0.0,0,0.0,0,0,0.0,0,0,6
4013,0,0,0,0.0,0,0,0,0,0.0,0.000000,...,0,0.0,0,0.0,0,0,0.0,0,0,2

In [4]:
# Map the cluster labels to their corresponding names
label_mapping = {
    0: 'L1',
    1: 'L1',
    2: 'B',
    3: 'B',
    4: 'L2',
    5: 'B',
    6: 'L2',
    7: 'Unclassified',
    8: 'Unclassified'
}

# Replace the values in the 'cluster_label' column
clustering_results['cluster_label'] = clustering_results['cluster_label'].map(label_mapping)

clustering_results.head()

,RP11.34P13.3,FAM138A,OR4F5,RP11.34P13.7,RP11.34P13.8,RP11.34P13.14,RP11.34P13.9,FO538757.3,FO538757.2,AP006222.2,...,BX072566.1,AL354822.1,AC023491.2,AC004556.1,AC233755.2,AC233755.1,AC240274.1,AC213203.1,FAM231B,cluster_label
0,0,0,0,0.0,0,0,0,0,0.0,0.000000,...,0,0.0,0,0.0,0,0,0.0,0,0,B
1,0,0,0,0.0,0,0,0,0,0.0,0.000000,...,0,0.0,0,0.0,0,0,0.0,0,0,B
2,0,0,0,0.0,0,0,0,0,0.0,0.000000,...,0,0.0,0,0.0,0,0,0.0,0,0,L1
3,0,0,0,0.0,0,0,0,0,0.0,0.592736,...,0,0.0,0,0.0,0,0,0.0,0,0,B
4,0,0,0,0.0,0,0,0,0,0.0,0.000000,...,0,0.0,0,0.0,0,0,0.0,0,0,L1

In [7]:
print(clustering_results['cluster_label'].value_counts())

L1              1931
B               1429
L2               572
Unclassified      82
Name: cluster_label, dtype: int64

In [8]:
clustering_results.to_csv('ind4_clustering_results.csv.gz', compression='gzip', index=False)