In [1]:
import pandas as pd

In [5]:
clustering_results = pd.read_csv('ind4_pca_embeddings_only_10PCs.csv')

In [6]:
clustering_results

,PC_1,PC_2,PC_3,PC_4,PC_5,PC_6,PC_7,PC_8,PC_9,PC_10,cluster_label
0,-18.265232,0.179890,2.512753,-0.017214,-1.253427,5.103237,3.069733,-1.498417,-0.213276,-1.921352,2
1,-11.648572,-2.388439,0.988511,3.860645,1.748230,0.217374,-0.771974,0.272593,1.387455,-0.643988,2
2,2.597364,-1.249371,-3.363064,-2.655913,-1.898509,-0.066221,-3.849705,2.200412,-2.473733,-0.130113,1
3,-3.417240,-4.438395,0.636533,3.351176,0.887752,-7.494596,-0.488962,0.585061,2.802112,-1.061658,3
4,7.382528,-0.940683,-9.480106,-6.126398,2.831281,1.671729,0.735573,-5.483888,3.156084,-4.968595,1
...,...,...,...,...,...,...,...,...,...,...,...
4009,8.322987,-3.214379,-0.689009,-0.262546,1.024876,-2.575015,-1.277584,2.146089,1.676037,0.391478,0
4010,-11.008588,-1.900832,-2.101015,2.335349,1.157123,-4.229745,0.003551,1.722289,-0.468227,2.221812,3
4011,9.320722,-5.689082,2.899196,2.080614,-1.207569,-1.014811,5.033344,2.736327,-3.361486,1.148018,0
4012,7.061739,10.454308,7.367766,7.623241,1.983226,1.349209,-3.744541,-8.520135,2.017838,1.947278,6
4013,-10.433870,-0.712840,4.045774,0.454931,-0.813817,9.411068,3.884733,-1.176880,0.834015,-2.175981,2

In [7]:
# Map the cluster labels to their corresponding names
label_mapping = {
    0: 'L1',
    1: 'L1',
    2: 'B',
    3: 'B',
    4: 'L2',
    5: 'B',
    6: 'L2',
    7: 'Unclassified',
    8: 'Unclassified'
}

# Replace the values in the 'cluster_label' column
clustering_results['cluster_label'] = clustering_results['cluster_label'].map(label_mapping)

clustering_results.head()

,PC_1,PC_2,PC_3,PC_4,PC_5,PC_6,PC_7,PC_8,PC_9,PC_10,cluster_label
0,-18.265232,0.179890,2.512753,-0.017214,-1.253427,5.103237,3.069733,-1.498417,-0.213276,-1.921352,B
1,-11.648572,-2.388439,0.988511,3.860645,1.748230,0.217374,-0.771974,0.272593,1.387455,-0.643988,B
2,2.597364,-1.249371,-3.363064,-2.655913,-1.898509,-0.066221,-3.849705,2.200412,-2.473733,-0.130113,L1
3,-3.417240,-4.438395,0.636533,3.351176,0.887752,-7.494596,-0.488962,0.585061,2.802112,-1.061658,B
4,7.382528,-0.940683,-9.480106,-6.126398,2.831281,1.671729,0.735573,-5.483888,3.156084,-4.968595,L1

In [ ]:
clustering_results.to_csv('ind4_clustering_10PCs.csv', index=False)